# Generated by Django 4.1.2 on 2022-10-31 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donvivttp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nguoidungthuocdonvi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sangkien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('author_2', models.CharField(blank=True, max_length=255)),
                ('author_3', models.CharField(blank=True, max_length=255)),
                ('cellphone', models.CharField(max_length=255)),
                ('idea_name', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=4000)),
                ('upload_file', models.FileField(blank=True, upload_to='')),
                ('note', models.TextField(blank=True, max_length=4000)),
                ('rank', models.CharField(blank=True, choices=[('I', 'Loại I'), ('II', 'Loại II'), ('III', 'Loại III'), ('KK', 'Khuyến Khích'), ('KĐ', 'Không Đạt cấp VTTP')], max_length=3)),
                ('status_approved', models.BooleanField(blank=True, default=False)),
                ('sent_VNPT', models.BooleanField(blank=True, default=False)),
                ('sent_sangtao_VNPT', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_created_by', to=settings.AUTH_USER_MODEL)),
                ('donvivttp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='sangkien.donvivttp')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sangkien',
            index=models.Index(fields=['id'], name='id_index_post'),
        ),
        migrations.AddIndex(
            model_name='donvivttp',
            index=models.Index(fields=['id'], name='id_index_topic'),
        ),
    ]
